version: 0.2

phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
      - echo installing dependencies...
      - npm install
      - npm install -g @angular/cli@10.1.1
    
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build
  post_build:
    commands:
        - aws s3 sync dist/ s3://naldes-s3 --delete    
artifacts:
  type: zip
  base-directory: "dist"
  files:
    - "**/*"
  
